"""Constants for the Heru integration."""

DOMAIN = "heru"
DEFAULT_NAME = "Heru"
DEFAULT_PORT = 502
DEFAULT_SLAVE = 1
UPDATE_INTERVAL_SECONDS = 15

HOLDING_REGISTER_USER_FAN_SPEED = 0
HOLDING_REGISTER_TEMPERATURE_SETPOINT = 1
